user/models.py
class User(object):
	"""
	User model for manipulating users collection
	structure = {
		"nick" : unicode,
		"fullname" : "",
		"email" : "",
		"favourites" : [],
		"roles" : [],
		"reputation" : int,
		"logins" : [{
			'ip' : unicode,
			'time' : datetime,
			'timezone' : unicode
		}],
		"about" : unicode
	}
	"""
	def __init__(self, db):
		self.db = db

	__collection__ = 'users'

	def insert(self, data):
		self.db[self.__collection__].insert(data)

	def validate(self, data):
		pass	

user/views.py
from flask import render_template, abort, url_for, request, redirect, session
from jinja2 import TemplateNotFound
from flask import Blueprint
from core import app, oid

import json

bp_user = Blueprint('bp_user', __name__, template_folder="templates")

@bp_user.route("/login")
@oid.loginhandler
def login():
	"""
	show login page
	"""
	try:
		if request.args.get("openid_identifier") is not None:
			openid = request.args.get("openid_identifier")
			return oid.try_login(openid, ask_for=['email', 'fullname',
												  'nickname', 'language', 'image', 'timezone'])
		else:
			return render_template("login.html", next=oid.get_next_url(), error = oid.fetch_error())
	except TemplateNotFound:
		app.logger.error("template user/login.html not found")
		abort(404)

@oid.after_login
def create_or_login(resp):
	app.logger.debug(json.dumps(resp))
	#session['openid'] = resp.identity_url

	#user = User.query.filter_by(openid=resp.identity_url).first()
	# if user is not None:
	#     flash(u'Successfully signed in')
	#     g.user = user
	#     return redirect(oid.get_next_url())
	return redirect(url_for('user_profile', next=oid.get_next_url(),
							name=resp.fullname or resp.nickname,
							email=resp.email))

@bp_user.route("/profile")
def user_profile():
	return json.dumps(request.args)

app.register_blueprint(bp_user)

user/templates/login.html
{% extends "base.html" %}

{% block title %}
	{{_("Login to your account using OpenID")}}
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{{url_for("static", filename="vendor/openid-selector/css/openid.css")}}" type="text/css" />
{% endblock %}

{% block javascripts %}
<script src="{{url_for("static", filename="vendor/openid-selector/js/openid-jquery.js")}}" type="text/javascript"></script>
<script src="{{url_for("static", filename="vendor/openid-selector/js/openid-en.js")}}" type="text/javascript"></script>
<script type="text/javascript">
	$(document).ready(function() {
		openid.img_path = "static/vendor/openid-selector/images/"
		openid.init('openid_identifier');
	});
</script>
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-lg-12">
		<form action="{{url_for("bp_user.login")}}" method="get" id="openid_form">
			<input type="hidden" name="action" value="verify" />
			<fieldset>
				<legend>{{ _("Sign-in or Create New Account") }}</legend>
				<div id="openid_choice">
					<p>{{_("Please click your account provider:")}}</p>
					<div id="openid_btns"></div>
				</div>
				<div id="openid_input_area">
					<input id="openid_identifier" name="openid_identifier" type="text" value="http://" />
					<input id="next" name="next" type="hidden" value="{{ next }}" />
					<input id="openid_submit" type="submit" value="Sign-In"/>
				</div>
				<noscript>
					<p>
					{% autoescape false %}
					{{ _("OpenID is service that allows you to log-on to many different websites using a single indentity.") }}
					{{
					_("Find out %(more_about_openid_link)s more about OpenID%(anchor_close)s and %(how_to_get_openid_link)s how to get an OpenID enabled account %(anchor_close)s.", 
							more_about_openid_link = '<a href="http://openid.net/what/">',
							anchor_close = "</a>",
							how_to_get_openid_link = '<a href="http://openid.net/get/">'
					 )
					}}
					{% endautoescape %}
				</p>
				</noscript>
			</fieldset>
		</form>
		{% if error %}
		<div class="has-error">
			<p class="help-block"><strong>{{_("Error:")}}</strong> {{ error }}</p>
		</div>
		{% endif %}
	</div>
</div>
{% endblock %}